# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '17.6.0'
        cache: 'npm'
        cache-dependency-path: ./package-lock.json

    - name: Install and test
      working-directory: .
      run: |
        npm install
        npm test

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag academy-final-cow:$(date +%s)

