# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '17.6.0'
        cache: 'npm'
        cache-dependency-path: ./package-lock.json

    - name: Install and test
      working-directory: .
      run: |
        npm install
        npm test
        
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.6
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag academy-final-cow:latest
      
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          
      
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: ${{ github.ref == 'refs/heads/main' }}
        tags: academyfinalproject.azurecr.io/academy-final-cow:latest

