name: Teaminator Frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "17.6.0"
          cache: "npm"
          cache-dependency-path: ./package-lock.json

      - name: Install and test
        working-directory: .
        run: |
          npm install
          npm test -- --coverage --testResultsProcessor=jest-sonar-reporter

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag academy-final-cow:latest
        
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
          record: true
          wait-on: 'http://localhost:3000'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Azure Container Registry Login
        if: github.ref == 'refs/heads/main'
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}

      - name: Build and push
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: academyfinalproject.azurecr.io/academy-final-cow:latest
