name: Teaminator Frontend Pull Request

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "17.6.0"
          cache: "npm"
          cache-dependency-path: ./package-lock.json

      - name: Install and test
        working-directory: .
        run: |
          npm install
          npm test -- --coverage --testResultsProcessor=jest-sonar-reporter

      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        env:
          CYPRESS_googleClientId: ${{ secrets.OAUTH_CLIENT_ID }}
          CYPRESS_googleClientSecret: ${{ secrets.OAUTH_SECRET }}
          CYPRESS_googleRefreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
        with:
          config: video=false
          start: npm run start
          wait-on: 'http://localhost:3000'

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
      - name: Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: './src/appSettings.json'
        env:
          apiUrl: ${{ secrets.API_URL }}
          googleClientId: ${{ secrets.REACT_APP_GOOGLE_CLIENTID }}
          heartBeatUrl: ${{ secrets.API_HEARTBEAT_URL }}

      - name: Build Docker image in Azure registry
        uses: docker/build-push-action@v2
        with:
          tags: academyfinalproject.azurecr.io/academy-final-cow:latest