name: Teaminator Frontend Merge

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: academyfinalproject.azurecr.io/academy-final-cow

      - name: Push Docker image to Azure registry
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}, academyfinalproject.azurecr.io/academy-final-cow:latest